--
-- PostgreSQL database dump
--

-- Dumped from database version 10.16
-- Dumped by pg_dump version 10.16

-- Started on 2025-05-29 22:33:00

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2900 (class 0 OID 0)
-- Dependencies: 2899
-- Name: DATABASE crypto_trade_history; Type: COMMENT; Schema: -; Owner: crypto_trade
--

COMMENT ON DATABASE crypto_trade_history IS 'historico del transaccional crypto_trade_db';


--
-- TOC entry 5 (class 2615 OID 42063)
-- Name: currencies; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA currencies;


ALTER SCHEMA currencies OWNER TO postgres;

--
-- TOC entry 9 (class 2615 OID 42064)
-- Name: users; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA users;


ALTER SCHEMA users OWNER TO postgres;

--
-- TOC entry 1 (class 3079 OID 12924)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2904 (class 0 OID 0)
-- Dependencies: 1
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


--
-- TOC entry 2 (class 3079 OID 42065)
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- TOC entry 2905 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 199 (class 1259 OID 42102)
-- Name: crypto_coin; Type: TABLE; Schema: currencies; Owner: postgres
--

CREATE TABLE currencies.crypto_coin (
    id integer NOT NULL,
    symbol character varying(10) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE currencies.crypto_coin OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 42109)
-- Name: crypto_coin_currency; Type: TABLE; Schema: currencies; Owner: crypto_trade
--

CREATE TABLE currencies.crypto_coin_currency (
    crypto_coin_id integer NOT NULL,
    currency_id integer NOT NULL
);


ALTER TABLE currencies.crypto_coin_currency OWNER TO crypto_trade;

--
-- TOC entry 201 (class 1259 OID 42112)
-- Name: crypto_coin_id_seq; Type: SEQUENCE; Schema: currencies; Owner: postgres
--

ALTER TABLE currencies.crypto_coin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME currencies.crypto_coin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 42114)
-- Name: currency; Type: TABLE; Schema: currencies; Owner: postgres
--

CREATE TABLE currencies.currency (
    id integer NOT NULL,
    symbol character varying(10) NOT NULL,
    name character varying(100) NOT NULL,
    country character varying(100),
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE currencies.currency OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 42118)
-- Name: currency_id_seq; Type: SEQUENCE; Schema: currencies; Owner: postgres
--

ALTER TABLE currencies.currency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME currencies.currency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 204 (class 1259 OID 42120)
-- Name: password_histories; Type: TABLE; Schema: users; Owner: postgres
--

CREATE TABLE users.password_histories (
    id integer NOT NULL,
    user_id integer NOT NULL,
    password_hash text NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE users.password_histories OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 42127)
-- Name: password_histories_id_seq; Type: SEQUENCE; Schema: users; Owner: postgres
--

ALTER TABLE users.password_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users.password_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 42129)
-- Name: sessions; Type: TABLE; Schema: users; Owner: postgres
--

CREATE TABLE users.sessions (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    user_id integer NOT NULL,
    session_start timestamp without time zone DEFAULT now() NOT NULL,
    last_activity timestamp without time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    ip_address character varying(255)
);


ALTER TABLE users.sessions OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 42136)
-- Name: user; Type: TABLE; Schema: users; Owner: postgres
--

CREATE TABLE users."user" (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    password_expires_at timestamp without time zone DEFAULT (now() + '90 days'::interval) NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE users."user" OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 42144)
-- Name: user_id_seq; Type: SEQUENCE; Schema: users; Owner: postgres
--

ALTER TABLE users."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2756 (class 2606 OID 42147)
-- Name: crypto_coin_currency crypto_coin_currency_pkey; Type: CONSTRAINT; Schema: currencies; Owner: crypto_trade
--

ALTER TABLE ONLY currencies.crypto_coin_currency
    ADD CONSTRAINT crypto_coin_currency_pkey PRIMARY KEY (crypto_coin_id, currency_id);


--
-- TOC entry 2752 (class 2606 OID 42149)
-- Name: crypto_coin crypto_coin_pkey; Type: CONSTRAINT; Schema: currencies; Owner: postgres
--

ALTER TABLE ONLY currencies.crypto_coin
    ADD CONSTRAINT crypto_coin_pkey PRIMARY KEY (id);


--
-- TOC entry 2754 (class 2606 OID 42151)
-- Name: crypto_coin crypto_coin_symbol_key; Type: CONSTRAINT; Schema: currencies; Owner: postgres
--

ALTER TABLE ONLY currencies.crypto_coin
    ADD CONSTRAINT crypto_coin_symbol_key UNIQUE (symbol);


--
-- TOC entry 2758 (class 2606 OID 42153)
-- Name: currency currency_pkey; Type: CONSTRAINT; Schema: currencies; Owner: postgres
--

ALTER TABLE ONLY currencies.currency
    ADD CONSTRAINT currency_pkey PRIMARY KEY (id);


--
-- TOC entry 2760 (class 2606 OID 42155)
-- Name: currency currency_symbol_key; Type: CONSTRAINT; Schema: currencies; Owner: postgres
--

ALTER TABLE ONLY currencies.currency
    ADD CONSTRAINT currency_symbol_key UNIQUE (symbol);


--
-- TOC entry 2762 (class 2606 OID 42157)
-- Name: password_histories password_histories_pkey; Type: CONSTRAINT; Schema: users; Owner: postgres
--

ALTER TABLE ONLY users.password_histories
    ADD CONSTRAINT password_histories_pkey PRIMARY KEY (id);


--
-- TOC entry 2764 (class 2606 OID 42159)
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: users; Owner: postgres
--

ALTER TABLE ONLY users.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- TOC entry 2766 (class 2606 OID 42161)
-- Name: user user_email_key; Type: CONSTRAINT; Schema: users; Owner: postgres
--

ALTER TABLE ONLY users."user"
    ADD CONSTRAINT user_email_key UNIQUE (email);


--
-- TOC entry 2768 (class 2606 OID 42163)
-- Name: user user_pkey; Type: CONSTRAINT; Schema: users; Owner: postgres
--

ALTER TABLE ONLY users."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- TOC entry 2769 (class 2606 OID 42164)
-- Name: crypto_coin_currency fkic0qamddir4gobbbknj54uyno; Type: FK CONSTRAINT; Schema: currencies; Owner: crypto_trade
--

ALTER TABLE ONLY currencies.crypto_coin_currency
    ADD CONSTRAINT fkic0qamddir4gobbbknj54uyno FOREIGN KEY (crypto_coin_id) REFERENCES currencies.crypto_coin(id);


--
-- TOC entry 2770 (class 2606 OID 42169)
-- Name: crypto_coin_currency fkmb0q94lagy7j5q3t8dlobb7qt; Type: FK CONSTRAINT; Schema: currencies; Owner: crypto_trade
--

ALTER TABLE ONLY currencies.crypto_coin_currency
    ADD CONSTRAINT fkmb0q94lagy7j5q3t8dlobb7qt FOREIGN KEY (currency_id) REFERENCES currencies.currency(id);


--
-- TOC entry 2771 (class 2606 OID 42174)
-- Name: password_histories password_histories_user_id_fkey; Type: FK CONSTRAINT; Schema: users; Owner: postgres
--

ALTER TABLE ONLY users.password_histories
    ADD CONSTRAINT password_histories_user_id_fkey FOREIGN KEY (user_id) REFERENCES users."user"(id);


--
-- TOC entry 2772 (class 2606 OID 42179)
-- Name: sessions sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: users; Owner: postgres
--

ALTER TABLE ONLY users.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users."user"(id);


--
-- TOC entry 2901 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA currencies; Type: ACL; Schema: -; Owner: postgres
--

GRANT USAGE ON SCHEMA currencies TO crypto_trade;


--
-- TOC entry 2903 (class 0 OID 0)
-- Dependencies: 9
-- Name: SCHEMA users; Type: ACL; Schema: -; Owner: postgres
--

GRANT USAGE ON SCHEMA users TO crypto_trade;


--
-- TOC entry 2906 (class 0 OID 0)
-- Dependencies: 199
-- Name: TABLE crypto_coin; Type: ACL; Schema: currencies; Owner: postgres
--

GRANT ALL ON TABLE currencies.crypto_coin TO crypto_trade;


--
-- TOC entry 2907 (class 0 OID 0)
-- Dependencies: 201
-- Name: SEQUENCE crypto_coin_id_seq; Type: ACL; Schema: currencies; Owner: postgres
--

GRANT ALL ON SEQUENCE currencies.crypto_coin_id_seq TO crypto_trade;


--
-- TOC entry 2908 (class 0 OID 0)
-- Dependencies: 202
-- Name: TABLE currency; Type: ACL; Schema: currencies; Owner: postgres
--

GRANT ALL ON TABLE currencies.currency TO crypto_trade;


--
-- TOC entry 2909 (class 0 OID 0)
-- Dependencies: 203
-- Name: SEQUENCE currency_id_seq; Type: ACL; Schema: currencies; Owner: postgres
--

GRANT ALL ON SEQUENCE currencies.currency_id_seq TO crypto_trade;


--
-- TOC entry 2910 (class 0 OID 0)
-- Dependencies: 204
-- Name: TABLE password_histories; Type: ACL; Schema: users; Owner: postgres
--

GRANT ALL ON TABLE users.password_histories TO crypto_trade;


--
-- TOC entry 2911 (class 0 OID 0)
-- Dependencies: 205
-- Name: SEQUENCE password_histories_id_seq; Type: ACL; Schema: users; Owner: postgres
--

GRANT ALL ON SEQUENCE users.password_histories_id_seq TO crypto_trade;


--
-- TOC entry 2912 (class 0 OID 0)
-- Dependencies: 206
-- Name: TABLE sessions; Type: ACL; Schema: users; Owner: postgres
--

GRANT ALL ON TABLE users.sessions TO crypto_trade;


--
-- TOC entry 2913 (class 0 OID 0)
-- Dependencies: 207
-- Name: TABLE "user"; Type: ACL; Schema: users; Owner: postgres
--

GRANT ALL ON TABLE users."user" TO crypto_trade;


--
-- TOC entry 2914 (class 0 OID 0)
-- Dependencies: 208
-- Name: SEQUENCE user_id_seq; Type: ACL; Schema: users; Owner: postgres
--

GRANT ALL ON SEQUENCE users.user_id_seq TO crypto_trade;


--
-- TOC entry 1737 (class 826 OID 42184)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: currencies; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA currencies REVOKE ALL ON SEQUENCES  FROM postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA currencies GRANT ALL ON SEQUENCES  TO crypto_trade;


--
-- TOC entry 1738 (class 826 OID 42185)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: currencies; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA currencies REVOKE ALL ON TABLES  FROM postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA currencies GRANT ALL ON TABLES  TO crypto_trade;


--
-- TOC entry 1739 (class 826 OID 42186)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: users; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA users REVOKE ALL ON SEQUENCES  FROM postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA users GRANT ALL ON SEQUENCES  TO crypto_trade;


--
-- TOC entry 1740 (class 826 OID 42187)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: users; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA users REVOKE ALL ON TABLES  FROM postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA users GRANT ALL ON TABLES  TO crypto_trade;


-- Completed on 2025-05-29 22:33:00

--
-- PostgreSQL database dump complete
--

